### PR TITLE
redundant (new keywords) code remove

### PR DESCRIPTION
**Pull request by Mamun361054**
there were some redundant keyword which not required removed

### CODE REVIEW

**Comment by christocracy** [comment]
If you’re going to *find/replace* text in source-code like this, you can’t do it with **Replace All** (or be **damn sure**}— you need to carefully cycle through and judge each with your eyes.

there are at least 2 cases where you’ve replaced the word “new” within doc-comments.

IMG_1328

IMG_1327

also, did you run `dart analyze` and `dart format` after this change?

**Comment by Mamun361054** [comment]
dart analyze and dart format 

> If you’re going to _find/replace_ text in source-code like this, you can’t do it with **Replace All** (or be **damn sure**}— you need to carefully cycle through and judge each with your eyes.
> 
> there are at least 2 cases where you’ve replaced the word “new” within doc-comments.
> 
> IMG_1328
> 
> IMG_1327
> 
> also, did you run `dart analyze` and `dart format` after this change?

yes , `dart analyze` and `dart format` executed successfully

**Comment by Mamun361054** [comment]
comment replace fixed

**Comment by Mamun361054** [comment]
let me know sir if you have facing any issues on this PR, i checked all good

**Comment by christocracy** [comment]
we *must not* have broken urls / images in the docs.

**Comment by christocracy** [comment]
The comments within the code are used for auto-generating the [API Docs](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/BackgroundGeolocation/requestTemporaryFullAccuracy.html).  The comments are *very* important.

**Comment by Mamun361054** [comment]
it will be taken care off from next time

**Pull request closed without merging**
